# Generated by Django 4.2 on 2023-08-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.IntegerField()),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=12)),
                ('role', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='seller_details',
            name='shop_add',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seller_details',
            name='shop_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
