# Generated by Django 4.2 on 2023-08-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder_app', '0003_rename_shop_name_seller_details_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_details',
            name='_ifsc',
            field=models.CharField(default='', max_length=17),
        ),
    ]
