# Generated by Django 4.2 on 2023-09-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder_app', '0006_food_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='city',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='state',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='zip',
            field=models.CharField(default='', max_length=15),
        ),
    ]
