# Generated by Django 4.2 on 2023-09-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder_app', '0008_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_details',
            name='location',
            field=models.CharField(default='', max_length=30),
        ),
    ]
