# Generated by Django 4.2 on 2023-10-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder_app', '0010_business_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.IntegerField()),
                ('food_name', models.CharField(max_length=25)),
                ('rating', models.CharField(max_length=10)),
                ('review', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=10)),
            ],
        ),
    ]
