# Generated by Django 4.2 on 2023-10-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder_app', '0012_shop_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='food_name',
        ),
    ]
