# Generated by Django 4.2 on 2023-10-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder_app', '0013_remove_review_food_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_review',
            name='business_name',
        ),
        migrations.AddField(
            model_name='shop_review',
            name='business_id',
            field=models.IntegerField(default=0),
        ),
    ]
