# Generated by Django 4.2 on 2023-10-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder_app', '0014_remove_shop_review_business_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shop_review',
        ),
    ]
