# Generated by Django 4.2 on 2023-10-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder_app', '0017_food_detail_avg_ratings_seller_details_avg_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_details',
            name='avg_ratings',
            field=models.IntegerField(default=1),
        ),
    ]
