# Generated by Django 4.2 on 2023-10-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder_app', '0018_alter_seller_details_avg_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('food_ids', models.CharField(default='', max_length=100)),
                ('total_price', models.IntegerField()),
            ],
        ),
    ]
