# Generated by Django 4.2 on 2023-10-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder_app', '0019_order_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_username', models.CharField(max_length=10)),
                ('food_id', models.IntegerField()),
                ('username', models.CharField(max_length=10)),
            ],
        ),
    ]
