# Generated by Django 4.2 on 2023-10-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder_app', '0020_order_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
